---
# tasks file for kurier

- name: configure raspbian
  import_tasks: raspbian.yml

- name: install pi-hole
  import_tasks: pi-hole.yml

- name: install MagicMirror
  import_tasks: magicMirror.yml

- name: reboot raspberry pi
  shell: reboot
  become: yes 
