- name: install vim
  apt:
    name: vim
    state: latest
  became: yes

- name: install httpie
  apt:
    name: httpie
    state: latest
  became: yes

- name: rotate screen
  lineinfile:
    path: /boot/config.txt
    line: 'display_rotate=3'
  register: display_rotated

- name: disable pointer
  apt:
    name: unclutter
    autoremove: yes
  register: pointer_disabled
