- name: rotate screen
  lineinfile:
    path: /boot/config.txt
    line: 'display_rotate=3'
  register: display_rotated

- name: disable pointer
  apt:
    name: unclutter
    autoremove: true
  register: pointer_disabled

- name: reboot 
  shell: reboot 
  when: display_rotated.changed or pointer_disabled.changed
