- name: install vim
  apt:
    name: vim
    state: latest
  become: yes

- name: install httpie
  apt:
    name: httpie
    state: latest
  become: yes

- name: rotate screen
  lineinfile:
    path: /usr/share/dispsetup.sh
    line: 'DISPLAY=:0 xrandr --output HDMI-1 --rotate left'
    insertbefore: 'exit 0'
  register: display_rotated
  become: yes

- name: disable pointer
  apt:
    name: unclutter
    autoremove: yes
  register: pointer_disabled
  become: yes
