- name: download imageSlideShow module
  git:
    repo: 'https://github.com/AdamMoses-GitHub/MMM-ImageSlideshow.git'
    dest: '{{ magicMirror_home }}/modules/MMM-ImageSlideshow'
    force: true

- name: configure imageSlideShow module
  blockinfile:
    block: "{{ lookup('file', 'mmm-imageSlideshow.js') }}"
    path: "{{ magicMirror_home }}/config/config.js"
    insertbefore: "//modules"
    marker: "// {mark} imageSlideshow module - ansible managed block"

- name: create images directory
  file: 
    path: '{{ magicMirror_home }}/modules/MMM-ImageSlideshow/images/desktop/'
    state: directory
    mode: 0755

- name: check directory has images
  find:
    paths: '{{ magicMirror_home }}/modules/MMM-ImageSlideshow/images/desktop/'
  register: imageSlideShow_images

- name: copy images
  copy: 
    src: '{{ images_source_path }}'
    dest: '{{ magicMirror_home }}/modules/MMM-ImageSlideshow/images/desktop/'
    follow: true
  when: imageSlideShow_images.examined == 0

